[patch.crates-io]
bitmesh = { git = "https://github.com/devinnicholson/bitmesh", rev = "410550c0964004cd7ba9677539f17ae82c139dd8" }
thermograph = { git = "https://github.com/devinnicholson/thermograph", rev = "32d6bfbc966f47a87e7249d4ed8818370288e079" }
